"""Tests for `utils.skill_doc_template`."""

import pytest

from utils.skill_doc_template import get_skill_templates_dir, load_template, render_template


def _base_context():
    return {
        "skill_name": "plan",
        "entrypoint": "nodes.plan:plan_node",
        "version": "1.0.0",
        "owner": "opc",
        "safety_level": "medium",
        "purpose": "Generate optimization plan from project context.",
        "inputs_markdown": "- project_path\n- optimization_goal\n- current_round",
        "outputs_markdown": "- current_plan\n- round_contract",
        "failure_handling": "Return legacy guidance and preserve previous plan.",
        "notes": "Auto-generated by template system.",
    }


def test_get_skill_templates_dir_exists():
    path = get_skill_templates_dir()
    assert path.endswith("skills")


def test_load_template_success():
    content = load_template("skill_doc.md.tmpl")
    assert "Skill: {skill_name}" in content


def test_render_template_success():
    rendered = render_template("skill_doc.md.tmpl", _base_context())
    assert "# Skill: plan" in rendered
    assert "Entrypoint: `nodes.plan:plan_node`" in rendered
    assert "Generate optimization plan" in rendered


def test_render_template_missing_key_raises():
    context = _base_context()
    context.pop("purpose")
    with pytest.raises(ValueError):
        render_template("skill_doc.md.tmpl", context)

