"""Generate skill markdown docs from registry + contracts + templates."""

import argparse
import os
import sys
from typing import List


def _project_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _ensure_project_root_on_path() -> None:
    root = _project_root()
    if root not in sys.path:
        sys.path.insert(0, root)


def _to_bullets(items: List[str]) -> str:
    if not items:
        return "- (none)"
    return "\n".join(f"- {item}" for item in items)


def _failure_handling_text(safety_level: str) -> str:
    if safety_level == "high":
        return "On failure, stop risky actions and fallback to legacy guidance."
    if safety_level == "medium":
        return "On failure, preserve state and mark round as partial."
    return "On failure, log warning and continue with conservative defaults."


def generate_skill_docs(output_dir: str | None = None, include_disabled: bool = False) -> List[str]:
    """Generate one markdown doc per skill and return generated file paths."""
    _ensure_project_root_on_path()
    from utils.skill_registry import build_core_skill_registry
    from utils.skill_contract import get_skill_contract
    from utils.skill_doc_template import render_template

    root = _project_root()
    target_dir = output_dir or os.path.join(root, "skills", "generated")
    os.makedirs(target_dir, exist_ok=True)

    registry = build_core_skill_registry()
    specs = registry.list(enabled_only=not include_disabled)

    generated: List[str] = []
    for spec in specs:
        contract = get_skill_contract(spec.name)
        context = {
            "skill_name": spec.name,
            "entrypoint": spec.entrypoint,
            "version": "1.0.0",
            "owner": "opc_optimizer",
            "safety_level": spec.safety_level,
            "purpose": spec.description,
            "inputs_markdown": _to_bullets(contract.required_inputs),
            "outputs_markdown": _to_bullets(contract.expected_outputs),
            "failure_handling": _failure_handling_text(spec.safety_level),
            "notes": "Generated by scripts/gen_skill_docs.py",
        }
        rendered = render_template("skill_doc.md.tmpl", context)
        out_path = os.path.join(target_dir, f"{spec.name}.md")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(rendered)
        generated.append(out_path)

    return generated


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate skill markdown docs.")
    parser.add_argument(
        "--output-dir",
        type=str,
        default="",
        help="Output directory for generated markdown files (default: skills/generated).",
    )
    parser.add_argument(
        "--include-disabled",
        action="store_true",
        help="Include disabled skills from registry.",
    )
    args = parser.parse_args()

    output_dir = args.output_dir.strip() or None
    generated = generate_skill_docs(
        output_dir=output_dir,
        include_disabled=args.include_disabled,
    )
    print(f"Generated {len(generated)} skill docs:")
    for path in generated:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
